ALTER TABLE delivery_record
    ADD COLUMN recipient_name VARCHAR(160) NOT NULL DEFAULT '',
    ADD COLUMN phone_number VARCHAR(40) NOT NULL DEFAULT '',
    ADD COLUMN address_line_1 VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN address_line_2 VARCHAR(255) NULL,
    ADD COLUMN city VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN state VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN postal_code VARCHAR(40) NOT NULL DEFAULT '',
    ADD COLUMN country VARCHAR(120) NOT NULL DEFAULT '';
