server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL:jdbc:mysql://mysql:3306/user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_APP_USER:appuser}
    password: ${MYSQL_APP_PASSWORD:apppass}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

