server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/product_db}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      acks: all
      properties:
        enable.idempotence: true

